#!/bin/sh
# szh install
sudo apt install zsh -y && \

# install curl
sudp apt install curl -y && \

# install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && \

# install normal theme
sed -e 's/robbyrussell/agnoster/' ~/.zshrc >> /dev/null && \

# put on plugins
sed -e 's/plugins=(git)/plugins=(git npm web-search)/' ~/.zshrc >> /dev/null && \

# install true fonts
sudo apt install fonts-powerline -y
